# Generated by Django 4.1.6 on 2023-02-23 08:50

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': [20.0, 10.0], 'marker_color': 'blue', 'marker_size': 'medium'}, null=True),
        ),
    ]
